package by.tms;

import by.tms.utils.DBUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

public class MainCreateBD {
    private static final String CREATE_TABLE_CITIES = """
            create table public.cities
            (
                id   integer generated by default as identity
                    constraint city_pk
                        primary key,
                name varchar(50) not null
                    constraint city_pk2
                        unique,
                info varchar(1000)
            )""";
    private static final String CREATE_TABLE_STUDENTS = """
            create table public.students
            (
                id      integer generated by default as identity
                    constraint student_pk
                        primary key,
                name    varchar(30) not null,
                surname varchar(50) not null,
                age     integer     not null,
                city    varchar(50)
                    constraint student_city_name_fk
                        references public.cities (name)
                        on delete cascade,
                course  varchar(30)
            )""";
    private static final String FILL_TABLE_CITIES = """
            INSERT INTO cities (name, info)
            VALUES ('Minsk',
                    'is the capital and the largest city of Belarus, located on the Svislach and the now subterranean Niamiha rivers.'),
                   ('New York', 'is the most populous city in the United States.'),
                   ('Warsaw', 'is the capital and largest city of Poland.')""";
    private static final String FILL_TABLE_STUDENTS = """
            INSERT INTO students (name, surname, age, city, course)
            VALUES ('Jerry', 'Carpenter', 18, 'Minsk', '22onl'),
                   ('Elizabeth', 'Sanders', 22, 'Warsaw', '22onl'),
                   ('Thelma', 'Anderson', 18, 'New York', '22onl'),
                   ('Jeremy', 'Palmer', 20, 'Minsk', '22onl'),
                   ('Harold', 'Mason', 35, 'Minsk', '22onl')""";

    public static void main(String[] args) {
        try (Connection connection = DBUtils.getConnection()) {
            PreparedStatement statementCreateCites = connection.prepareStatement(CREATE_TABLE_CITIES);
            PreparedStatement statementFillCites = connection.prepareStatement(FILL_TABLE_CITIES);
            PreparedStatement statementCreateStudents = connection.prepareStatement(CREATE_TABLE_STUDENTS);
            PreparedStatement statementFillStudents = connection.prepareStatement(FILL_TABLE_STUDENTS);
            List<PreparedStatement> statements = List.of(statementCreateCites, statementFillCites, statementCreateStudents, statementFillStudents);
            for (PreparedStatement statement : statements) {
                statement.execute();
            }
        } catch (SQLException e) {
            System.out.println("Exception: " + e.getMessage());
        }
    }
}