drop table if exists cities cascade;

drop table if exists students cascade;

create table public.cities
(
    id   integer generated by default as identity
        constraint city_pk
            primary key,
    name varchar(50) not null
        constraint city_pk2
            unique,
    info varchar(1000)
);

alter table public.cities
    owner to postgres;

create table public.students
(
    id      integer generated by default as identity
        constraint student_pk
            primary key,
    name    varchar(30) not null,
    surname varchar(50) not null,
    age     integer     not null,
    city    varchar(50)
        constraint student_city_name_fk
            references public.cities (name)
            on delete cascade,
    course  varchar(30)
);

comment
    on table public.students is 'students_db for lesson21';

alter table public.students
    owner to postgres;

INSERT INTO cities (name, info)
VALUES ('Minsk',
        'is the capital and the largest city of Belarus, located on the Svislach and the now subterranean Niamiha rivers.'),
       ('New York', 'is the most populous city in the United States.'),
       ('Warsaw', 'is the capital and largest city of Poland.');

INSERT INTO cities (name)
VALUES ('Boston');

INSERT INTO students (name, surname, age, city, course)
VALUES ('Jerry', 'Carpenter', 18, 'Minsk', '22onl'),
       ('Elizabeth', 'Sanders', 22, 'Warsaw', '22onl'),
       ('Thelma', 'Anderson', 18, 'New York', '22onl'),
       ('Jeremy', 'Palmer', 20, 'Minsk', '22onl'),
       ('Harold', 'Mason', 35, 'Minsk', '22onl');