create table public.students
(
    id      integer generated by default as identity
        constraint student_pk
            primary key,
    name    varchar(30) not null,
    surname varchar(50) not null,
    age     integer     not null,
    city    varchar(50)
        constraint student_city_name_fk
            references public.cities (name)
            on delete cascade,
    course  varchar(30)
);

comment
on table public.students is 'student_db for lesson21';

alter table public.students
    owner to postgres;